export const ActionTypes = {
    ADD_IDEAS: "ADD_IDEAS",
    SET_IDEAS: "SET_IDEAS",
    SELECTED_IDEAS: "SELECTED_IDEAS",
    SELECTED_IDEAS_SUCCESS: "SELECTED_IDEAS_SUCCESS",
    DELETE_SELECTED_IDEAS: "DELETE_SELECTED_IDEAS",
    UPDATE_IDEAS: "UPDATE_IDEAS",
    UPDATE_IDEAS_SUCCESS: "UPDATE_IDEAS_SUCCESS",
    DELETE_IDEAS: "DELETE_IDEAS",
    DELETE_IDEAS_SUCCESS: "DELETE_IDEAS_SUCCESS",
    SET_IDEAS_SUCCESS:"SET_IDEAS_SUCCESS"
};