export const ActionTypes = {
    ADD_IDEAS: "ADD_IDEAS",
    SET_IDEAS: "SET_IDEAS",
    SELECTED_IDEAS: "SELECTED_IDEAS",
    DELETE_SELECTED_IDEAS: "DELETE_SELECTED_IDEAS",
    UPDATE_IDEAS: "UPDATE_IDEAS",
    DELETE_IDEAS: "DELETE_IDEAS"
};